name: CI Test Subgraph Locally

on:
  # triggered by internal pushes
  push:
    branches-ignore: ["master", "dev"]
  # triggered by external PRs (filtered in the `check` job)
  pull_request:

jobs:
  test-subgraph:
    name: Build and test subgraph (Feature Branch)

    runs-on: ubuntu-latest
    
    env:
      subgraph-working-directory: ./packages/subgraph
      contracts-working-directory: ./packages/ethereum-contracts
      sdk-working-directory: ./packages/js-sdk

    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      
      - name: "Install yarn"
        run: npm install -g yarn ganache-cli
      
      # at some point we want to install ganache-cli

      - name: "Install contract dependencies"
        run: yarn install
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Build contracts"
        run: yarn run build:contracts
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Install subgraph dependencies"
        run: yarn install
        working-directory: ${{ env.subgraph-working-directory }}

      - name: "Get ABI for subgraph.yaml"
        run: node scripts/getAbi.js
        working-directory: ${{ env.subgraph-working-directory }}

      - name: "Run ganache-cli node"
        run: ganache-cli -h 0.0.0.0 -m "test test test test test test test test test test test junk" &
        working-directory: ${{ env.subgraph-working-directory }}

      - name: "Get abi.js file for js-sdk to deploy locally"
        run: |
          chmod +x ./tasks/build-abi-js.sh
          ./tasks/build-abi-js.sh
        working-directory: ${{ env.sdk-working-directory }}

      - name: "Deploy contracts and token locally"
        run: npx hardhat run test/deployContractsAndToken.ts --network localhost
        working-directory: ${{ env.subgraph-working-directory }}

      - name: "install docker compose"
        run: npm install -g docker-compose


      - name: "Checkout graph node repo and set up local graph node"
        uses: actions/checkout@v2
        with:
          repository: graphprotocol/graph-node
          path: docker
          token: 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

      - name: "test???"
        run: |
          ls -la
          chmod +x setup.sh
          ./setup.sh
          docker-compose up &
        working-directory: ./docker/docker

      - name: "Prepare, build and deploy subgraph locally"
        run: yarn prepare && yarn build && deploy-local
        working-directory: ${{ env.subgraph-working-directory }}

      